inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# 文字数上限
LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.circleci/*'
    - 'docker-compose.yml'
    - 'docker-compose.ci.yml'
    - 'Dockerfile.dev'
    - 'Dockerfile.ci'
